### PR TITLE
Change `EventType` to an interface with a type argument

### LINKED ISSUE #109: Type for EventItem incorrect
EventItem definition is incorrect, for example there is no `type` member in the docs

https://github.com/screepers/typed-screeps/blob/da98868f43a1fcea0939ead877444448f098f0ac/src/literals.ts#L448-L457

See https://docs.screeps.com/api/#Room.getEventLog, it is called `event`

### PR DESCRIPTION
**Pull request by Arcath**
### Brief Description

Change `EventType` to an interface with a type argument so that the `data` attribute can be typed implicitly. For example, once you set the event type to `EventType<EVENT_ATTACK>` the data takes on the type `EventData[EVENT_ATTACK]`. This also lets the type of data be addressable so you can write functions that expect a certain type of event data.

This also fixes #109 as `EventType` incorrectly used _type_ instead of _event_.

### Checklists

- [x] Test passed
- [x] Coding style (indentation, etc)
- [x] Edits have been made to `src/` files not `index.d.ts`
- [x] Run `npm run dtslint` to update `index.d.ts`

### CODE REVIEW

File: dist/index.d.ts [hunk 1]
```diff
@@ -1949,87 +1949,55 @@ type EVENT_HEAL_TYPE_RANGED = 2;
...
-                };
-      };
+interface EventItem<T extends EventConstant = EventConstant> {
+    event: T;
+    objectId: string;
+    data: EventData[T];
+}
+
+interface EventData {
+    [key: number]: null | object;
```
Comment (riggs) [inline dist/index.d.ts]:
```suggestion
    [key: number]: null | any;
```
Type `object` has no properties. [Playground](http://www.typescriptlang.org/play/#src=interface%20With_Object%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20number%5D%3A%20null%20%7C%20object%0D%0A%7D%0D%0Alet%20with_object%3A%20With_Object%20%3D%20%7B%7D%3B%0D%0A%0D%0Ainterface%20With_Any%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20number%5D%3A%20null%20%7C%20any%0D%0A%7D%0D%0Alet%20with_any%3A%20With_Any%20%3D%20%7B%7D%3B%0D%0A%0D%0Atype%20Foo%20%3D%20%7B%20foo%3A%20string%20%7D%0D%0A%0D%0Awith_object%5B42%5D%20%3D%20%7B%20foo%3A%20%22foo%22%20%7D%0D%0A%0D%0Alet%20foo%3A%20Foo%20%3D%20with_object%5B42%5D%3B%0D%0A%0D%0Awith_any%5B42%5D%20%3D%20%7B%20foo%3A%20%22bar%22%20%7D%0D%0A%0D%0Alet%20bar%3A%20Foo%20%3D%20with_any%5B42%5D%3B%0D%0A%0D%0Aif%20(with_object%5B42%5D.property%20%3D%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%2F%2F...%0D%0A%7D%0D%0A%0D%0Aif%20(with_any%5B42%5D.property%20%3D%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%2F%2F...%0D%0A%7D)

File: src/literals.ts [hunk 2]
```diff
@@ -445,84 +445,52 @@ type EVENT_HEAL_TYPE_RANGED = 2;
...
-                };
-      };
+interface EventItem<T extends EventConstant = EventConstant> {
+    event: T;
+    objectId: string;
+    data: EventData[T];
+}
+
+interface EventData {
+    [key: number]: null | object;
```
Comment (riggs) [inline src/literals.ts]: See above

**Comment by Arcath** [comment]
I've updated the type to something that better describes the return data, it's either `null` or an object that might have these properties.

The index type is only there so typescript will let you address it as `EventData[X]` which is how the `EventItem` type works.

**Comment by Meekohi** [comment]
Awesome :D
